### ISSUE TITLE
Move to Tensorflow2

### ISSUE THREAD

**Issue by GeorgeLiang3** [gknilsen/pyhessian#2]
Hi @gknilsen , ever thought to move to Tensorflow 2?

**Comment by gknilsen** [comment]
Hello @GeorgeLiang3, so far I have only done some testing in TF2 using tensorflow.compat.v1 and disable_v2_behavior(). It was mostly to experiment with the TF_DETERMINISTIC_OPS flag. But generally I don't have much time to think about moving it currently.

**Comment by GeorgeLiang3** [comment]
Thanks for your reply @gknilsen, quite interesting work
